#!/usr/bin/env python3
"""Generate ticket status views from the ticket files.

Each ticket's `- Status:` header line is the only place status is written. This script
derives everything else from it:

- `<root>/tickets/STATUS.md` — every initiative and milestone, what is in progress, blocked and
  next ready, open plan questions, plus consistency problems.
- The ledger table inside each initiative `index.md`, between the ledger markers.

Working order is the order tickets are listed under `## Tickets` in each milestone index,
milestones in folder order.

The project root is the folder holding `tickets/` and `knowledge/`: a repo's own `jrg/`, or a
project's folder in a hub. With no root given, the script uses the folder it lives in, which is
the in-repo case.

Usage:
    python3 status.py [ROOT]           regenerate the views
    python3 status.py [ROOT] --check   exit 1 if the views are stale or problems exist
"""

import re
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve()
ARGS = [a for a in sys.argv[1:] if not a.startswith("--")]
if ARGS:  # hub: the script sits at the hub root, the project is an argument
    TICKETS = Path(ARGS[0]).expanduser().resolve() / "tickets"
    ROOT = SCRIPT.parent
    CMD = f"python3 status.py {TICKETS.parent.relative_to(ROOT).as_posix()}"
else:  # in-repo: the script sits in <repo>/jrg/tickets/
    TICKETS = SCRIPT.parent
    ROOT = TICKETS.parent.parent
    CMD = f"python3 {SCRIPT.relative_to(ROOT).as_posix()}"
PLANS = TICKETS.parent / "knowledge" / "plans"
STATUS_FILE = TICKETS / "STATUS.md"
HOLDING_LISTS = ("deferred", "backlog", "pre-migration")
STATUSES = ("todo", "in_progress", "blocked", "awaiting_merge", "done", "cancelled")
CLOSED = ("done", "cancelled")
LEDGER_BEGIN = "<!-- ledger:begin — generated by status.py; edit ticket Status lines instead -->"
LEDGER_END = "<!-- ledger:end -->"

LINK = re.compile(r"\[([^\]]+)\]\(([^)#\s]+)")


def header(text, field):
    m = re.search(rf"^- {field}:\s*(.*)$", text, re.M)
    return m.group(1).strip() if m else None


def links(value):
    return [href for _, href in LINK.findall(value or "")]


def section(text, heading):
    m = re.search(rf"^## {re.escape(heading)}\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1) if m else ""


class Ticket:
    def __init__(self, path, milestone):
        self.path = path
        self.milestone = milestone
        text = path.read_text()
        m = re.match(r"#\s+(\S+)\s+—\s+(.+)", text)
        self.id, self.title = (m.group(1), m.group(2).strip()) if m else (path.stem, path.stem)
        self.status = header(text, "Status")
        self.type = header(text, "Type") or ""
        self.branch = header(text, "Branch")
        self.depends = [(path.parent / h).resolve() for h in links(header(text, "Depends on"))]
        parent = links(header(text, "Parent"))
        self.parent = (path.parent / parent[0]).resolve() if parent else None
        nm = re.search(r"^Next:\s*(.+)$", section(text, "Notes and blockers"), re.M)
        self.next = nm.group(1).strip() if nm else None


class Milestone:
    def __init__(self, folder):
        self.folder = folder
        self.index = folder / "index.md"
        text = self.index.read_text()
        m = re.match(r"#\s+(.+)", text)
        self.name = m.group(1).strip() if m else folder.name
        self.short = re.sub(r"^M\d+\s+—\s+", "", self.name)
        self.listed = [(folder / h).resolve() for h in links(section(text, "Tickets"))]
        evidence = section(text, "Outcome evidence").strip()
        self.exit_recorded = bool(evidence) and not evidence.startswith("Not completed")
        self.tickets = []


class Initiative:
    def __init__(self, folder):
        self.folder = folder
        self.index = folder / "index.md"
        m = re.match(r"#\s+(.+)", self.index.read_text())
        self.name = m.group(1).strip() if m else folder.name
        self.milestones = [Milestone(f) for f in sorted(folder.iterdir())
                           if f.is_dir() and re.match(r"\d+-", f.name) and (f / "index.md").exists()]


def load():
    problems = []
    initiatives = [Initiative(f) for f in sorted(TICKETS.iterdir())
                   if f.is_dir() and f.name not in HOLDING_LISTS + ("templates",)
                   and (f / "index.md").exists()]
    by_path, ids = {}, {}
    for ini in initiatives:
        for ms in ini.milestones:
            files = {p.resolve() for p in ms.folder.glob("*.md") if p.name != "index.md"}
            for p in ms.listed:
                if p not in files:
                    problems.append(f"{rel(ms.index)} lists a missing ticket: {rel(p)}")
                elif ms.listed.count(p) > 1:
                    problems.append(f"{rel(ms.index)} lists {rel(p)} more than once")
            for p in sorted(files - set(ms.listed)):
                problems.append(f"{rel(p)} is not listed in {rel(ms.index)}")
            seen = set()
            for p in [p for p in ms.listed if p in files] + sorted(files - set(ms.listed)):
                if p in seen:
                    continue
                seen.add(p)
                t = Ticket(p, ms)
                ms.tickets.append(t)
                by_path[p] = t
                if t.id in ids:
                    problems.append(f"duplicate ID {t.id}: {rel(p)} and {rel(ids[t.id])}")
                ids[t.id] = p
                if t.status not in STATUSES:
                    problems.append(f"{t.title}: invalid or missing Status ({t.status!r})")
                if t.status in ("in_progress", "blocked") and not t.next:
                    problems.append(f"{t.title}: {t.status} but has no Next: line")
    for t in by_path.values():
        for d in t.depends:
            if d not in by_path:
                problems.append(f"{t.title}: Depends on a missing ticket {rel(d)}")
        if t.parent:
            if t.parent not in by_path:
                problems.append(f"{t.title}: Parent is missing {rel(t.parent)}")
            elif t.path not in by_path[t.parent].depends:
                problems.append(f"{by_path[t.parent].title}: does not depend on its sub-ticket {t.title}")
        if t.status == "done":
            for d in t.depends:
                if d in by_path and by_path[d].status not in CLOSED:
                    problems.append(f"{t.title}: done while dependency {by_path[d].title} is {by_path[d].status}")
    return initiatives, by_path, problems


def rel(p):
    try:
        return str(Path(p).relative_to(ROOT))
    except ValueError:
        return str(p)


def link_from(src_dir, target):
    return Path(*[".."] * len(src_dir.relative_to(TICKETS).parts), target.relative_to(TICKETS)).as_posix() \
        if src_dir != TICKETS else target.relative_to(TICKETS).as_posix()


def ready(t, by_path):
    return t.status == "todo" and all(by_path[d].status == "done" for d in t.depends if d in by_path)


def milestone_state(ms):
    statuses = [t.status for t in ms.tickets]
    if statuses and all(s in CLOSED for s in statuses):
        return "complete" if ms.exit_recorded else "tickets closed, exit not recorded"
    if any(s != "todo" for s in statuses):
        return "in progress"
    return "not started"


def count_entries(name):
    text = (TICKETS / name / "index.md").read_text()
    entries = text.split("\n## Entries", 1)
    return len(re.findall(r"^## ", entries[1], re.M)) if len(entries) == 2 else 0


def groomed(name):
    m = re.search(r"^- \*\*Last groomed:\*\*\s*(.+?)\.?$", (TICKETS / name / "index.md").read_text(), re.M)
    return m.group(1) if m else "unknown"


def open_questions():
    """(plan name, link, open count, parked count) for every plan with a decision register."""
    found = []
    for reg in sorted(PLANS.glob("*/decisions.md")) if PLANS.is_dir() else []:
        text = reg.read_text().split("\n## Questions", 1)[-1]
        opened = len(re.findall(r"^- Status:\s*open\b", text, re.M))
        parked = len(re.findall(r"^- Status:\s*parked\b", text, re.M))
        if opened or parked:
            link = Path("..", reg.relative_to(TICKETS.parent)).as_posix()
            found.append((reg.parent.name, link, opened, parked))
    return found


def render_status(initiatives, by_path, problems):
    out = ["# Status", "",
           f"Generated by `{CMD}` from each ticket's `Status` line. Do not edit.", ""]
    if problems:
        out += ["## Problems", ""] + [f"- {p}" for p in problems] + [""]

    def row(t):
        where = f"{t.milestone.short}"
        parent = by_path.get(t.parent)
        if parent:
            where += f", sub-ticket of {parent.title}"
        return f"- [{t.title}]({link_from(TICKETS, t.path)}) ({where})"

    active = [t for t in by_path.values() if t.status == "in_progress"]
    blocked = [t for t in by_path.values() if t.status == "blocked"]
    out += ["## In progress", ""]
    out += [f"{row(t)}\n  - Next: {t.next or '—'}" for t in active] or ["None."]
    out += ["", "## Blocked", ""]
    out += [f"{row(t)}\n  - Next: {t.next or '—'}" for t in blocked] or ["None."]
    merging = [t for t in by_path.values() if t.status == "awaiting_merge"]
    if merging:
        out += ["", "## Awaiting merge", ""]
        out += [f"{row(t)}\n  - Branch: {t.branch or '—'}" for t in merging]
    out += ["", "## Next ready", "",
            "First `todo` in working order whose dependencies are done. Check its milestone's entry conditions before starting.", ""]
    for ini in initiatives:
        nxt = next((t for ms in ini.milestones for t in ms.tickets if ready(t, by_path)), None)
        out.append(f"- {ini.name}: " + (row(nxt)[2:] if nxt else "nothing ready"))
    out += ["", "## Initiatives and milestones", ""]
    for ini in initiatives:
        tickets = [t for ms in ini.milestones for t in ms.tickets]
        closed = sum(t.status in CLOSED for t in tickets)
        out += [f"### [{ini.name}]({link_from(TICKETS, ini.index)}) — {closed}/{len(tickets)} closed", "",
                "| Milestone | State | Done | In progress | Blocked | Todo |",
                "| --- | --- | --- | --- | --- | --- |"]
        for ms in ini.milestones:
            c = {s: sum(t.status == s for t in ms.tickets) for s in STATUSES}
            done = c["done"] + c["cancelled"]
            out.append(f"| [{ms.name}]({link_from(TICKETS, ms.index)}) | {milestone_state(ms)} | "
                       f"{done}/{len(ms.tickets)} | {c['in_progress'] + c['awaiting_merge']} | {c['blocked']} | {c['todo']} |")
        out.append("")
    questions = open_questions()
    if questions:
        out += ["## Open plan questions", ""]
        out += [f"- [{name}]({link}): {o} open, {p} parked" for name, link, o, p in questions]
        out.append("")
    out += ["## Holding lists", ""]
    for name in HOLDING_LISTS:
        if not (TICKETS / name / "index.md").exists():
            continue
        out.append(f"- [{name.capitalize()}]({name}/index.md): {count_entries(name)} entries, last groomed {groomed(name)}")
    return "\n".join(out) + "\n"


def render_ledger(ini):
    rows = ["| ID | Ticket | Type | Status |", "| --- | --- | --- | --- |"]
    for ms in ini.milestones:
        for t in ms.tickets:
            rows.append(f"| {t.id} | [{t.title}]({t.path.relative_to(ini.folder).as_posix()}) | {t.type} | {t.status} |")
    return "\n".join([LEDGER_BEGIN] + rows + [LEDGER_END])


def with_ledger(ini, problems):
    text = ini.index.read_text()
    pattern = re.compile(r"<!-- ledger:begin.*?-->.*?" + re.escape(LEDGER_END), re.S)
    if not pattern.search(text):
        problems.append(f"{rel(ini.index)} has no ledger markers; ledger not generated")
        return text
    return pattern.sub(lambda _: render_ledger(ini), text)


def main():
    check = "--check" in sys.argv[1:]
    initiatives, by_path, problems = load()
    outputs = {ini.index: with_ledger(ini, problems) for ini in initiatives}
    outputs[STATUS_FILE] = render_status(initiatives, by_path, problems)
    stale = [p for p, body in outputs.items() if not p.exists() or p.read_text() != body]
    if check:
        for p in stale:
            print(f"stale: {rel(p)} (run {CMD})")
    else:
        for p in stale:
            p.write_text(outputs[p])
            print(f"wrote {rel(p)}")
    for p in problems:
        print(f"problem: {p}")
    print(f"{len(by_path)} tickets, {len(problems)} problems")
    sys.exit(1 if problems or (check and stale) else 0)


if __name__ == "__main__":
    main()
